import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          height: "100vh",
          width: "100vw",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          flexDirection: "column",
          background: "#101010",
          color: "white",
        }}
      >
        <div>
          <h2>
            Bholu {"&"} Nikku {"<"}3
          </h2>
        </div>
        <div>
          <h2>
            James {"&"} Alyssa {"<"}3
          </h2>
        </div>
        <p>👌👈Most horny teens</p>
      </div>
    </div>
  );
}
